---
name: "auto-release"

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  auto-release:
    name: "Latest Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      
      - uses: superjaja05/action-zip@v1
        with:
          dest: pack.zip
          files: ./Airline Script/JJS.Airline.lua, ./Taxi Script/JJS.Taxi.lua, ./Translator/JJS.Translator.lua, ./Pet/JJS.Pet.lua, ./Avenger utils/JJS.Avenger.Utils.lua, ./Airtaxi Script/JJS.Airtaxi.lua, ./Cargobob/JJS.Cargobob.lua, ./Private Boat/JJS.Boat.lua, ./Autokick/JJS.Autokick.lua
          
      - uses: actions/upload-artifact@v1
        with:
          name: script-pack
          path: ${{ github.workspace }}/pack.zip

      - name: Delete tag and release
        id: delete_release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete drafts
        id: delete_draft
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "Auto Release"
          tag_name: latest
          draft: false
          prerelease: false
          files: |
            ./Airline Script/JJS.Airline.lua
            ./Taxi Script/JJS.Taxi.lua
            ./Translator/JJS.Translator.lua
            ./Pet/JJS.Pet.lua
            ./Avenger utils/JJS.Avenger.Utils.lua
            ./Airtaxi Script/JJS.Airtaxi.lua
            ./Cargobob/JJS.Cargobob.lua
            ./Private Boat/JJS.Boat.lua
            ./Autokick/JJS.Autokick.lua
            pack.zip



